name: Build and Deploy
on:
  push:
    branches:
      - release/*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: yarn
      - name: Create .env file for staging
        run: echo "${{ secrets.ENV_STAGING }}" > .env
        if: endsWith(github.ref, '/staging')
      - name: Create .env file for production
        run: echo "${{ secrets.ENV_PRODUCTION }}" > .env
        if: endsWith(github.ref, '/production')
      - name: Build
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
      - name: Deploy to Firebase for staging
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID_STAGING }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_STAGING }}
        if: endsWith(github.ref, '/staging')
      - name: Deploy to Firebase for production
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID_PRODUCTION }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_PRODUCTION }}
        if: endsWith(github.ref, '/production')
